/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Frontend Interview API
 * Backend API for frontend developer interview task
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

/**
 * * `email` - email
* `phone` - phone
* `both` - both
 */
export type ContactMethodEnum = typeof ContactMethodEnum[keyof typeof ContactMethodEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContactMethodEnum = {
  email: 'email',
  phone: 'phone',
  both: 'both',
} as const;

/**
 * Serializer for CropRecord model.
 */
export interface CropRecord {
  readonly id: number;
  /** @maxLength 100 */
  crop_name: string;
  /** @maxLength 100 */
  variety: string;
  /** @maxLength 150 */
  scientific_name?: string;
  /** @maxLength 50 */
  field_id: string;
  /** @maxLength 20 */
  plot_number: string;
  /** @maxLength 100 */
  region: string;
  /** @maxLength 100 */
  country: string;
  /**
   * @nullable
   * @pattern ^-?\d{0,3}(?:\.\d{0,7})?$
   */
  latitude?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,3}(?:\.\d{0,7})?$
   */
  longitude?: string | null;
  /** @maxLength 50 */
  soil_type: string;
  /** @maxLength 50 */
  irrigation_type: string;
  /** @maxLength 50 */
  growing_season: string;
  planting_date: string;
  /** @nullable */
  expected_harvest_date?: string | null;
  /** @nullable */
  actual_harvest_date?: string | null;
  /**
   * Yield in kg/hectare
   * @nullable
   * @pattern ^-?\d{0,8}(?:\.\d{0,2})?$
   */
  yield_amount?: string | null;
  /** @maxLength 10 */
  yield_quality_grade?: string;
  /**
   * @nullable
   * @pattern ^-?\d{0,4}(?:\.\d{0,2})?$
   */
  plant_height_cm?: string | null;
  /** @maxLength 100 */
  fertilizer_type?: string;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  fertilizer_amount_kg?: string | null;
  pesticide_applied?: boolean;
  /** @maxLength 100 */
  pesticide_type?: string;
  status?: StatusEnum;
  /**
   * @nullable
   * @pattern ^-?\d{0,3}(?:\.\d{0,2})?$
   */
  avg_temperature_c?: string | null;
  /**
   * @nullable
   * @pattern ^-?\d{0,6}(?:\.\d{0,2})?$
   */
  total_rainfall_mm?: string | null;
  /** @maxLength 100 */
  researcher_name?: string;
  notes?: string;
  readonly created_at: string;
  readonly updated_at: string;
}

/**
 * Lightweight serializer for list view (fewer fields for performance).
 */
export interface CropRecordList {
  readonly id: number;
  /** @maxLength 100 */
  crop_name: string;
  /** @maxLength 100 */
  variety: string;
  /** @maxLength 50 */
  field_id: string;
  /** @maxLength 100 */
  region: string;
  /** @maxLength 100 */
  country: string;
  status?: StatusEnum;
  planting_date: string;
  /**
   * Yield in kg/hectare
   * @nullable
   * @pattern ^-?\d{0,8}(?:\.\d{0,2})?$
   */
  yield_amount?: string | null;
  /** @maxLength 10 */
  yield_quality_grade?: string;
  /** @maxLength 100 */
  researcher_name?: string;
  readonly created_at: string;
}

export type ErrorResponseDetails = {[key: string]: unknown};

/**
 * Error response serializer.
 */
export interface ErrorResponse {
  error: string;
  details?: ErrorResponseDetails;
}

/**
 * Serializer for form submission with 10 input fields.
Includes various validation rules for demonstration.
 */
export interface FormSubmission {
  /**
   * Full name (3-100 characters)
   * @minLength 3
   * @maxLength 100
   */
  full_name: string;
  /** Valid email address */
  email: string;
  /**
   * Phone number (optional)
   * @maxLength 20
   */
  phone?: string;
  /**
   * Age (1-150)
   * @minimum 1
   * @maximum 150
   */
  age?: number;
  /** Website URL (optional) */
  website?: string;
  /**
   * Short bio (max 500 characters)
   * @maxLength 500
   */
  bio?: string;
  /**
   * Country name
   * @maxLength 100
   */
  country?: string;
  /** Must agree to terms and conditions */
  agree_terms: boolean;
  /** Preferred contact method

* `email` - email
* `phone` - phone
* `both` - both */
  contact_method: ContactMethodEnum;
}

/**
 * Serializer for form submission with 10 input fields.
Includes various validation rules for demonstration.
 */
export interface FormSubmissionRequest {
  /**
   * Full name (3-100 characters)
   * @minLength 3
   * @maxLength 100
   */
  full_name: string;
  /**
   * Valid email address
   * @minLength 1
   */
  email: string;
  /**
   * Password (minimum 8 characters, must contain uppercase, lowercase, and number)
   * @minLength 8
   * @maxLength 128
   */
  password: string;
  /**
   * Phone number (optional)
   * @maxLength 20
   */
  phone?: string;
  /**
   * Age (1-150)
   * @minimum 1
   * @maximum 150
   */
  age?: number;
  /** Website URL (optional) */
  website?: string;
  /**
   * Short bio (max 500 characters)
   * @maxLength 500
   */
  bio?: string;
  /**
   * Country name
   * @maxLength 100
   */
  country?: string;
  /** Must agree to terms and conditions */
  agree_terms: boolean;
  /** Preferred contact method

* `email` - email
* `phone` - phone
* `both` - both */
  contact_method: ContactMethodEnum;
}

/**
 * Response serializer for form submission.
 */
export interface FormSubmissionResponse {
  message: string;
  submission_id: string;
  data: FormSubmission;
}

/**
 * Serializer for user login.
 */
export interface LoginRequest {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
}

/**
 * Serializer for logout request.
 */
export interface LogoutRequest {
  /** @minLength 1 */
  refresh: string;
}

/**
 * Generic message response serializer.
 */
export interface MessageResponse {
  message: string;
}

/**
 * Serializer for paginated crop data response.
 */
export interface PaginatedCropResponse {
  /** Total number of items */
  count: number;
  /** Current page number */
  page: number;
  /** Number of items per page */
  page_size: number;
  /** Total number of pages */
  total_pages: number;
  /**
   * URL to next page
   * @nullable
   */
  next: string | null;
  /**
   * URL to previous page
   * @nullable
   */
  previous: string | null;
  results: CropRecordList[];
}

/**
 * Serializer for user registration.
 */
export interface SignupRequest {
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @minLength 1
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @minLength 1 */
  email: string;
  /** @minLength 1 */
  password: string;
  /** @minLength 1 */
  password_confirm: string;
  /**
   * @minLength 2
   * @maxLength 30
   */
  first_name: string;
  /**
   * @minLength 2
   * @maxLength 30
   */
  last_name: string;
}

/**
 * * `planned` - Planned
* `planted` - Planted
* `growing` - Growing
* `flowering` - Flowering
* `harvested` - Harvested
* `failed` - Failed
 */
export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StatusEnum = {
  planned: 'planned',
  planted: 'planted',
  growing: 'growing',
  flowering: 'flowering',
  harvested: 'harvested',
  failed: 'failed',
} as const;

export interface TokenRefresh {
  readonly access: string;
  refresh: string;
}

export interface TokenRefreshRequest {
  /** @minLength 1 */
  refresh: string;
}

/**
 * Serializer for token response.
 */
export interface TokenResponse {
  access: string;
  refresh: string;
  user: User;
}

/**
 * Serializer for user information.
 */
export interface User {
  readonly id: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @maxLength 150
   * @pattern ^[\w.@+-]+$
   */
  username: string;
  /** @maxLength 254 */
  email?: string;
  /** @maxLength 150 */
  first_name?: string;
  /** @maxLength 150 */
  last_name?: string;
}

export type AuthLoginCreateParams = {
/**
 * Set to true to simulate a server error (for testing)
 */
simulate_error?: boolean;
};

export type AuthLogoutCreateParams = {
/**
 * Set to true to simulate a server error (for testing)
 */
simulate_error?: boolean;
};

export type AuthSignupCreateParams = {
/**
 * Set to true to simulate a server error (for testing)
 */
simulate_error?: boolean;
};

export type FormSubmitCreateParams = {
/**
 * Set to true to simulate a server error (for testing)
 */
simulate_error?: boolean;
};

export type TableDataRetrieveParams = {
/**
 * Filter by country (partial match)
 */
country?: string;
/**
 * Filter by crop name (partial match)
 */
crop_name?: string;
/**
 * Sort by field (prefix with - for descending)
 */
ordering?: TableDataRetrieveOrdering;
/**
 * Page number (default: 1)
 */
page?: number;
/**
 * Items per page: 10, 25, 50, or 100 (default: 10)
 */
page_size?: TableDataRetrievePageSize;
/**
 * Filter by region (partial match)
 */
region?: string;
/**
 * Search across crop_name, variety, region, country, researcher_name
 */
search?: string;
/**
 * Set to true to simulate a server error (for testing)
 */
simulate_error?: boolean;
/**
 * Filter by status (exact match)
 */
status?: TableDataRetrieveStatus;
/**
 * Filter by variety (partial match)
 */
variety?: string;
};

export type TableDataRetrieveOrdering = typeof TableDataRetrieveOrdering[keyof typeof TableDataRetrieveOrdering];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TableDataRetrieveOrdering = {
  '-country': '-country',
  '-created_at': '-created_at',
  '-crop_name': '-crop_name',
  '-id': '-id',
  '-planting_date': '-planting_date',
  '-status': '-status',
  '-yield_amount': '-yield_amount',
  country: 'country',
  created_at: 'created_at',
  crop_name: 'crop_name',
  id: 'id',
  planting_date: 'planting_date',
  status: 'status',
  yield_amount: 'yield_amount',
} as const;

export type TableDataRetrievePageSize = typeof TableDataRetrievePageSize[keyof typeof TableDataRetrievePageSize];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TableDataRetrievePageSize = {
  NUMBER_10: 10,
  NUMBER_100: 100,
  NUMBER_25: 25,
  NUMBER_50: 50,
} as const;

export type TableDataRetrieveStatus = typeof TableDataRetrieveStatus[keyof typeof TableDataRetrieveStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TableDataRetrieveStatus = {
  failed: 'failed',
  flowering: 'flowering',
  growing: 'growing',
  harvested: 'harvested',
  planned: 'planned',
  planted: 'planted',
} as const;

/**
 * Authenticate a user with username and password. Returns JWT tokens on success.
 * @summary Login user
 */
export const authLoginCreate = <TData = AxiosResponse<TokenResponse>>(
    loginRequest: LoginRequest,
    params?: AuthLoginCreateParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/login/`,
      loginRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Logout the current user by blacklisting the refresh token.
 * @summary Logout user
 */
export const authLogoutCreate = <TData = AxiosResponse<MessageResponse>>(
    logoutRequest: LogoutRequest,
    params?: AuthLogoutCreateParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/logout/`,
      logoutRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Create a new user account with the provided credentials. Returns JWT tokens on success.
 * @summary Register a new user
 */
export const authSignupCreate = <TData = AxiosResponse<TokenResponse>>(
    signupRequest: SignupRequest,
    params?: AuthSignupCreateParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/signup/`,
      signupRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Takes a refresh type JSON web token and returns an access type JSON web
token if the refresh token is valid.
 */
export const authTokenRefreshCreate = <TData = AxiosResponse<TokenRefresh>>(
    tokenRefreshRequest: TokenRefreshRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/token/refresh/`,
      tokenRefreshRequest,options
    );
  }

/**
 * Returns the profile information of the currently authenticated user.
 * @summary Get current user profile
 */
export const authUserRetrieve = <TData = AxiosResponse<User>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/auth/user/`,options
    );
  }

/**
 * Returns detailed information about a specific crop record.
 * @summary Get crop record by ID
 */
export const cropsRetrieve = <TData = AxiosResponse<CropRecord>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/crops/${id}/`,options
    );
  }

/**
 * 
Submit a form with 10 input fields. The form includes:
- **full_name**: Required, 3-100 characters
- **email**: Required, valid email format
- **password**: Required, min 8 chars, must contain uppercase, lowercase, and digit
- **phone**: Optional phone number
- **age**: Optional, 1-150
- **website**: Optional URL
- **bio**: Optional, max 500 characters
- **country**: Optional country name
- **agree_terms**: Required, must be true
- **contact_method**: Required, one of: email, phone, both

If contact_method is 'phone' or 'both', phone number becomes required.
        
 * @summary Submit form data
 */
export const formSubmitCreate = <TData = AxiosResponse<FormSubmissionResponse>>(
    formSubmissionRequest: FormSubmissionRequest,
    params?: FormSubmitCreateParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/form/submit/`,
      formSubmissionRequest,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 
Returns paginated crop science data for display in a crops.

**Pagination:**
- `page`: Page number (default: 1)
- `page_size`: Number of items per page (10, 25, 50, 100) - default: 10

**Filtering:**
- `crop_name`: Filter by crop name (partial match)
- `country`: Filter by country (partial match)
- `region`: Filter by region (partial match)
- `status`: Filter by status (exact match: planned, planted, growing, flowering, harvested, failed)
- `variety`: Filter by variety (partial match)

**Sorting:**
- `ordering`: Field to sort by. Prefix with `-` for descending order.
  - Options: id, crop_name, variety, country, region, status, planting_date, yield_amount, created_at

The response includes pagination metadata and a list of crop records.
        
 * @summary Get paginated crop data
 */
export const tableDataRetrieve = <TData = AxiosResponse<PaginatedCropResponse>>(
    params?: TableDataRetrieveParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/table/data/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

export type AuthLoginCreateResult = AxiosResponse<TokenResponse>
export type AuthLogoutCreateResult = AxiosResponse<MessageResponse>
export type AuthSignupCreateResult = AxiosResponse<TokenResponse>
export type AuthTokenRefreshCreateResult = AxiosResponse<TokenRefresh>
export type AuthUserRetrieveResult = AxiosResponse<User>
export type CropsRetrieveResult = AxiosResponse<CropRecord>
export type FormSubmitCreateResult = AxiosResponse<FormSubmissionResponse>
export type TableDataRetrieveResult = AxiosResponse<PaginatedCropResponse>
